server:
  port: ${BACKEND_SERVER_PORT:9090}

spring:
  application:
    name: gallery-processor
  threads:
    virtual:
      enabled: true
  thread-executor: virtual
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${BACKEND_DATASOURCE_URL:jdbc:postgresql://localhost:5432/furizon}
    username: ${BACKEND_DATASOURCE_USERNAME:user}
    password: ${BACKEND_DATASOURCE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

security:
  http-password: ${HTTP_BASIC_AUTH_PASSWORD:password}
  http-username: ${HTTP_BASIC_AUTH_USER:user}

logbook:
  format:
    style: http
  httpclient:
    decompress-response: true

springdoc:
  api-docs:
    path: /docs/api-docs
    enabled: ${DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${DOCS_ENABLED:false}

worker:
  delay: ${WORKER_DELAY_SECS:20}
  max-retries: ${WORKER_JOB_MAX_RETRIES:5}
  quality: ${THUMBNAIL_QUALITY:85}
  job-completed-webhook:
    user: ${JOB_COMPLETED_WEBHOOK_USER:changeme}
    password: ${JOB_COMPLETED_WEBHOOK_PASSWORD:changeme}
    url: ${JOB_COMPLETED_WEBHOOK_URL:}
  render-prefix: ${THUMBNAIL_REDER_PREFIX:rend_}
  thumbnail-prefix: ${THUMBNAIL_REDER_PREFIX:thumb_}
  thumbnail:
    max-dimension: ${THUMBNAIL_DIMENSION:512}
    min-dimension: ${THUMBNAIL_DIMENSION:128}
    video-max-seek: ${THUMBNAIL_VIDEO_MAX_SEEK_SEC:3}

s3:
  access-key: ${S3_ACCESS_KEY:changeme}
  secret-key: ${S3_SECRET_KEY:changeme}
  endpoint: ${S3_ENDPOINT:}
  region: ${S3_REGION:changeme}
  bucket: ${S3_BUCKET:changeme}
  bucket-path-style: ${S3_BUCKET_PATH_STYLE:false}
  multipart-size: ${S3_MULTIPART_PART_SIZE:6291456} #6 MB
  presign-expiration-mins: ${S3_PRESIGN_EXPIRATION_MINS:15}

cmd-executor:
  imagemagick-binary: ${CMD_IMAGEMAGICK_BINARY:}
  ffmpeg-binary: ${CMD_FFMPEG_BINARY:ffmpeg}
  ffprobe-binary: ${CMD_FFPROBE_BINARY:ffprobe}
  timeout: ${CMD_TIMEOUT_SECS:30}

